//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Chess.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_CHESS_DIALOG                102
#define IDR_MAINFRAME                   128
#define IDD_REPORT                      129
#define IDI_REDO                        130
#define IDD_DIALOG1                     130
#define IDD_THINKOPTION                 130
#define IDI_HELP                        131
#define IDD_OPEN                        131
#define IDI_UNDO                        132
#define IDD_OPTION                      133
#define IDI_DIR                         133
#define IDD_BAI                         134
#define IDR_MENUBAI                     135
#define IDR_MENUBAIMAIN                 145
#define IDI_B_K                         152
#define IDI_B_S                         153
#define IDI_B_X                         154
#define IDI_B_M                         155
#define IDI_B_J                         156
#define IDI_B_P                         157
#define IDI_B_B                         158
#define IDI_R_K                         159
#define IDI_R_S                         160
#define IDI_R_X                         161
#define IDI_R_M                         162
#define IDI_R_J                         163
#define IDI_R_P                         164
#define IDI_R_B                         165
#define IDI_CUT                         166
#define IDC_CHESS_UNDO                  1001
#define IDC_CHESS_HELP                  1002
#define IDC_CHESS_REDO                  1003
#define IDC_LIST2                       1004
#define IDC_CHESS_CUT                   1004
#define IDC_STATIC1                     1005
#define IDC_RADIOMAN1                   1006
#define IDC_RADIOCOM1                   1007
#define IDC_BUTTONWEB                   1007
#define IDC_STATIC2                     1008
#define IDC_BUTTONEMAIL                 1008
#define IDC_RADIOMAN2                   1009
#define IDC_PROGRESS1                   1009
#define IDC_RADIOCOM2                   1010
#define IDC_RADIOMODE1                  1011
#define IDC_EDITS1                      1011
#define IDC_RADIOMODE2                  1012
#define IDC_RADIOMODE3                  1013
#define IDC_EDITLEVEL1                  1015
#define ID_MYOK                         1015
#define IDC_SPIN1                       1016
#define IDC_DIR                         1016
#define IDC_FILELIST                    1017
#define IDC_RESET                       1019
#define IDC_RADIO_GOSIDE_RED            1021
#define IDC_RADIO_GOSIDE_BLACK          1022
#define IDC_BAIOK                       1023
#define IDC_BT_NORMAL                   1024
#define IDC_BT_CLEAR                    1025
#define IDC_STEPLIST                    1026
#define IDC_EDITX1                      1029
#define IDC_SPIN2                       1030
#define IDC_BT_OPEN                     1031
#define IDC_EDITM1                      1031
#define IDC_BT_SAVE                     1032
#define IDC_SPIN3                       1032
#define IDC_EDITJ1                      1033
#define IDC_SPIN4                       1034
#define IDC_EDITP1                      1035
#define IDC_SPIN5                       1036
#define IDC_EDITB1                      1037
#define IDC_SPIN6                       1038
#define IDC_EDITS2                      1039
#define IDC_SPIN7                       1040
#define IDC_EDITX2                      1041
#define IDC_SPIN8                       1042
#define IDC_EDITM2                      1043
#define IDC_SPIN9                       1044
#define IDC_EDITJ2                      1045
#define IDC_SPIN10                      1046
#define IDC_EDITP2                      1047
#define IDC_SPIN11                      1048
#define IDC_EDITB2                      1049
#define IDC_SPIN12                      1050
#define IDC_EDIT30                      1057
#define IDC_SPIN13                      1058
#define IDC_EDIT31                      1059
#define IDC_SPIN14                      1060
#define IDC_EDIT32                      1061
#define IDC_SPIN15                      1062
#define IDC_EDIT33                      1063
#define IDC_SPIN16                      1064
#define IDC_EDIT34                      1069
#define IDC_SPIN17                      1070
#define ID_FILE_BAI                     32771
#define ID_HELP_EMAIL                   32772
#define ID_HELP_WEB                     32773
#define ID_CHESS_CUT                    32774
#define ID_FILE_OPTION                  32775
#define ID_ABOUTBOX                     32776
#define ID_FILE_THINKOPTION             32777
#define ID_BAI_DELETE                   32778
#define ID_BAI_CANCEL                   32779
#define ID_HELP_USE                     32779
#define ID_RED_B                        32780
#define ID_RED_P                        32781
#define ID_RED_J                        32782
#define ID_RED_K                        32783
#define ID_RED_M                        32784
#define ID_RED_X                        32785
#define ID_RED_S                        32786
#define ID_BLACK_B                      32787
#define ID_BLACK_P                      32788
#define ID_BLACK_J                      32789
#define ID_BLACK_M                      32790
#define ID_BLACK_X                      32791
#define ID_BLACK_S                      32792
#define ID_BLACK_K                      32793
#define ID_CHESS_UNDO                   32797
#define ID_CHESS_REDO                   32798
#define ID_CHESS_HELP                   32799
#define ID_VIEW_REPORT                  32800

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         32780
#define _APS_NEXT_CONTROL_VALUE         1018
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
