/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class wu_a_jni_JniBase */

#ifndef _Included_wu_a_jni_JniBase
#define _Included_wu_a_jni_JniBase
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     wu_a_jni_JniBase
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_wu_a_jni_JniBase_getName
  (JNIEnv *, jclass);

/*
 * Class:     wu_a_jni_JniBase
 * Method:    getAge
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_wu_a_jni_JniBase_getAge
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
