/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_enc_ntv_EncDemoLib */

#ifndef _Included_com_mog_EncDemo_EncDemoLib
#define _Included_com_mog_EncDemo_EncDemoLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_enc_ntv_EncDemoLib
 * Method:    EncryptFile
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_com_mog_EncDemo_EncDemoLib_EncryptFile
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_enc_ntv_EncDemoLib
 * Method:    DecryptFile
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_com_mog_EncDemo_EncDemoLib_DecryptFile
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
